const ADD_INGS = "ADD_INGS";
const REMOVE_INGS = "REMOVE_INGS";
const SET_INGS = "SET_INGS";
const INGS_ERROR = "INGS_ERROR";

const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export {
  ADD_INGS,
  REMOVE_INGS,
  SET_INGS,
  INGS_ERROR,
  PURCHASE_BURGER_SUCCESS,
  PURCHASE_BURGER_FAIL,
};
