export const ADD_INGS = "ADD_INGS";
export const REMOVE_INGS = "REMOVE_INGS";
export const SET_INGS = "SET_INGS";
export const INGS_ERROR = "INGS_ERROR";

export const PURCHASE_STARTED = "PURCHASE_STARTED";
export const PURCHASE_SUCCEEDED = "PURCHASE_SUCCEEDED";
export const PURCHASE_FAILED = "PURCHASE_FAILED";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_STARTED = "FETCH_ORDERS_STARTED";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_SUCCEEDED = "FETCH_ORDERS_SUCCEEDED";
export const REMOVE_ORDER = "REMOVE_ORDER";
