const ADD_INGS = "ADD_INGS";
const REMOVE_INGS = "REMOVE_INGS";
const SET_INGS = "SET_INGS";
const INGS_ERROR = "INGS_ERROR";

const PURCHASE_STARTED = "PURCHASE_STARTED";
const PURCHASE_SUCCEEDED = "PURCHASE_SUCCEEDED";
const PURCHASE_FAILED = "PURCHASE_FAILED";
const PURCHASE_INIT = "PURCHASE_INIT";
export {
  ADD_INGS,
  REMOVE_INGS,
  SET_INGS,
  INGS_ERROR,
  PURCHASE_STARTED,
  PURCHASE_SUCCEEDED,
  PURCHASE_FAILED,
  PURCHASE_INIT,
};
